[package]
name = "ihsiok"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua = { version = "^0.19.7", features=["system-luajit"], default-features = false }